[package]
name = "cadena-perpetua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arraystring = "0.3.0"
curl = "0.4.43"
rand = "0.8.5"
